language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coverage codecov
script:
  - python setup.py flake8
  - coverage run --source=petriish/ setup.py test
  - codecov
